# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fetch Data

on:
  schedule:
  - cron: "*/55 * * * *"
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup Dependencies
      run: |
        pip3 install requests
        
    - uses: actions/checkout@v2
    - name: Fetching Data
      run: |
        python gen.py
        
    - name: Uploading Files
      uses: actions/checkout@v2
      with:
        name: my-artifact
        path: "*.json"


