# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fetch Data

on:
  schedule:
  - cron: "*/55 * * * *"
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup Dependencies
      run: |
        pip3 install requests
        
    - uses: actions/checkout@v2
    - name: Fetching Data
      run: |
        python gen.py
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r output.zip output
        
    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output.zip
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "Auto Release System...."


